[package]
name = "qr_web"
version = "0.5.0"
edition = "2021"
description = "WebAssembly frontend for qr-scan-rs"
license = "MIT OR Apache-2.0"
authors = ["Bhavik <limanibhavik@gmail.com>"]
repository = "https://github.com/LimaniBhavik/qr.rs"

[dependencies]
qr-rs = { path = "../", version = "0.5.0", package="qr-scan-rs" }
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["HtmlInputElement", "HtmlTextAreaElement", "InputEvent"] }
gloo = { version = "0.11", features = ["futures"] }
gloo-console = "0.3"
base64 = "0.21"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "png_generation_bench"
harness = false

[[bench]]
name = "yew_bench"
harness = false

[[bin]]
name = "qr_web"
path = "src/main.rs"
