use crate::error::QRError;
use crate::formats::{format_url, generate_vcard, QRData};
use image::{DynamicImage, ImageFormat, Luma, Rgba, RgbaImage};
use imageproc::drawing::draw_filled_rect_mut;
use imageproc::rect::Rect;
use qrcode::QrCode;
use std::io::Cursor;

pub struct QRGenerator {
    pub error_correction: qrcode::EcLevel,
    pub foreground_color: Rgba<u8>,
    pub background_color: Rgba<u8>,
}

impl Default for QRGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl QRGenerator {
    pub fn new() -> Self {
        Self {
            error_correction: qrcode::EcLevel::H,
            foreground_color: Rgba([0, 0, 0, 255]), // Black
            background_color: Rgba([255, 255, 255, 255]), // White
        }
    }

    pub fn with_error_correction(mut self, level: qrcode::EcLevel) -> Self {
        self.error_correction = level;
        self
    }

    pub fn with_colors(mut self, foreground: [u8; 4], background: [u8; 4]) -> Self {
        self.foreground_color = Rgba(foreground);
        self.background_color = Rgba(background);
        self
    }

    pub fn generate(&self, data: &QRData) -> Result<QrCode, QRError> {
        let content = match data {
            QRData::URL(url) => format_url(url),
            QRData::Text(text) => text.clone(),
            QRData::Contact(contact) => generate_vcard(contact),
        };

        QrCode::with_error_correction_level(content, self.error_correction)
            .map_err(|e| QRError::GenerationError(e.to_string()))
    }

    pub fn to_image(&self, qr: &QrCode, size: u32, logo: Option<&DynamicImage>) -> Result<DynamicImage, QRError> {
        let qr_image = qr.render::<Luma<u8>>().min_dimensions(size, size).build();
        let width = qr_image.width();
        let height = qr_image.height();

        let mut image = RgbaImage::new(width, height);

        for (x, y, pixel) in qr_image.enumerate_pixels() {
            let color = if pixel.0[0] == 0 {
                self.foreground_color
            } else {
                self.background_color
            };
            image.put_pixel(x, y, color);
        }

        // Ensure quiet zone (padding) is respected and colored correctly
        // The qrcode crate's render() adds a quiet zone, but we want to make sure
        // we're using the custom background color.
        // Actually, the above loop covers the entire image generated by qrcode crate,
        // which includes the quiet zone (white by default in Luma<u8> render, so it maps to background_color).

        if let Some(logo_img) = logo {
            // Calculate logo size (e.g., 20% of QR code size)
            let logo_size = (width as f32 * 0.2) as u32;
            let logo_resized = logo_img.resize(logo_size, logo_size, image::imageops::FilterType::Lanczos3);

            let x_offset = (width - logo_resized.width()) / 2;
            let y_offset = (height - logo_resized.height()) / 2;

            // Optional: Draw a background rectangle for the logo to improve readability
            // This clears the QR code data behind the logo
            // This is simple but effectively relies on Error Correction to recover data
            // Since we default to H (High) error correction, we can cover up to 30% of the code.

            // Draw background for logo using background color
            let rect = Rect::at(x_offset as i32, y_offset as i32)
                .of_size(logo_resized.width(), logo_resized.height());
            draw_filled_rect_mut(&mut image, rect, self.background_color);

            image::imageops::overlay(&mut image, &logo_resized, x_offset as i64, y_offset as i64);
        }

        Ok(DynamicImage::ImageRgba8(image))
    }

    pub fn to_png(&self, qr: &QrCode, size: u32, logo: Option<&DynamicImage>) -> Result<Vec<u8>, QRError> {
        let image = self.to_image(qr, size, logo)?;

        let mut bytes: Vec<u8> = Vec::new();
        let mut cursor = Cursor::new(&mut bytes);
        image
            .write_to(&mut cursor, ImageFormat::Png)
            .map_err(|e| QRError::GenerationError(e.to_string()))?;

        Ok(bytes)
    }

    pub fn to_svg(&self, qr: &QrCode) -> String {
        let mut binding = qr.render::<qrcode::render::svg::Color>();
        let builder = binding.min_dimensions(200, 200);

        // Use default colors for now as leaking string memory is unsafe for long running processes
        // A proper SVG generation with custom colors would require avoiding .leak() which is intended for 'static str
        // For the purpose of this refactor, we will maintain the black/white default for SVG
        // or implement a custom SVG renderer if needed.
        // Given the constraints, we'll revert to default SVG generation but keep the structure.

        builder.build()
    }
}
